
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:db/test-data.sql
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
jwt:
  secret: "test-secret-test-secret-test-secret-test-secret"
  expirationMillis: 3600000

library:
  rental:
    max-active: 3
